-- Ejecuta TODO este archivo en:
-- Supabase > SQL Editor > New query

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  day_number integer not null unique check (day_number > 0),
  title text not null check (char_length(title) <= 120),
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- Cualquiera puede LEER los mensajes, porque la página de Honey es pública.
drop policy if exists "Public can read messages" on public.messages;
create policy "Public can read messages"
on public.messages
for select
to anon, authenticated
using (true);

-- Solo usuarios autenticados pueden crear, editar o borrar.
-- IMPORTANTE: desactiva los nuevos registros (Signups) en Supabase Auth
-- para que solo exista tu cuenta de administrador.

drop policy if exists "Authenticated can insert messages" on public.messages;
create policy "Authenticated can insert messages"
on public.messages
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update messages" on public.messages;
create policy "Authenticated can update messages"
on public.messages
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete messages" on public.messages;
create policy "Authenticated can delete messages"
on public.messages
for delete
to authenticated
using (true);
